### ISSUE TITLE
Error: ConnectFailure (Connection refused). 

### ISSUE THREAD

**Issue by brianraila** [santedb/hello-mpi#1]
@justin-fyfe
 
I keep getting this error while trying to setup SanteDB MPI using this example.

```
(WebException) : {"$type":"WebException","message":"Error: ConnectFailure (Connection refused)","cause":{"data":[],"$type":"SocketException","message":"Connection refused","policyOutcome":"Deny"},"policyOutcome":"Deny","data":[]}
```

**Comment by justin-fyfe** [comment]
Please see the tutorial for ensuring that the iCDR is also setup:

https://help.santesuite.org/installation/quick-start-guide

If using the SDK you will need to use the IP/PORT you have exposed from Docker or the development machine when joining the domain (so instead of santedb-mpi:8080 which is the internal docker host name you'd use localhost:8080)

Video tutorials for reference:

Docker: https://youtu.be/klQxQx_kgMw
Windows: https://youtu.be/OoFmllu6M34
Linux: https://youtu.be/CH7WbCqQySk

**Comment by brianraila** [comment]
Thanks alot Justin.
Got it working now. 😊
